source_file: "Adobe Photoshop Lightroom.XMP"
exif: {
  comment: "No EXIF data"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  comment: "no image data"
}
video_phash: {
  comment: "no video data"
}
