source_file:  "BigBuckBunny.ts"
want_err:  true
want_fingerprint:  {
  want_kind:  "VideoPHashRicop"
  want_hash:  "52c4fd5de1755969.5aaad654a92a5595"
  want_quality:  20
}
xmp:  {
  comment:  "No XMP data"
}
video_phash:  {
  want_ricop_hash:  "52c4fd5de1755969.5aaad654a92a5595"
}
