source_file:  "BigBuckBunny.mp4"
want_err:  true
want_fingerprint:  {
  want_kind:  "VideoPHashRicop"
  want_hash:  "58c54663613cd75a.2a55aa55aa55aa55"
  want_quality:  20
}
xmp:  {
  comment:  "No XMP data"
}
video_phash:  {
  want_ricop_hash:  "58c54663613cd75a.2a55aa55aa55aa55"
}
