source_file:  "heic.digital iPad Air 5th gen 1.heic"
want_err:  true
want_fingerprint:  {
  want_kind:  "ImgPHashAzr"
  want_hash:  "cc622b0ccb946767"
  want_quality:  20
}
want_fingerprint:  {
  want_kind:  "ImgPHashNr90"
  want_hash:  "ff7b7b7178000000.393d18383c0f3991"
  want_quality:  20
}
xmp:  {}
img_phash:  {
  want_azr_hash:  "cc622b0ccb946767"
  want_nr90_hash:  "ff7b7b7178000000.393d18383c0f3991"
}
