source_file: "heic.digital iPhone 12 Pro 2.heic"
want_fingerprint: {
  want_kind: "EXIFModelSerialPhotoID"
  want_hash: "Apple iPhone 12 Pro  8836E8B5-A132-4292-8D7D-87CCE1CACD2A"
  want_quality: 100
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "788e0831fcff1f00"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "7070f0f0f0f0f03.93c3c2c2c3c39119"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "LjI0Hw23I7HYk00+nI7A7H5P2w3k3IZJbk5b2QHgoHA4HA4fZHYDYHA8H4PAG5LLcDE4PA3AB4bJ7J7H4/HwH4/NjY5Hg8HA"
  want_quality: 20
}
exif: {
  want_camera_model: "Apple iPhone 12 Pro"
  want_photo_id: "8836E8B5-A132-4292-8D7D-87CCE1CACD2A"
  want_unique_photo_id: true
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "788e0831fcff1f00"
  want_nr90_hash: "7070f0f0f0f0f03.93c3c2c2c3c39119"
}
video_phash: {
  comment: "No Video Data"
  skip: true
}
