source_file:  "heic.digital iPhone 12 Pro 2.heic"
want_err:  true
want_fingerprint:  {
  want_kind:  "ImgPHashAzr"
  want_hash:  "788e0831fcff1f00"
  want_quality:  20
}
want_fingerprint:  {
  want_kind:  "ImgPHashNr90"
  want_hash:  "7070f0f0f0f0f03.93c3c2c2c3c39119"
  want_quality:  20
}
xmp:  {
  comment:  "No XMP data"
}
img_phash:  {
  want_azr_hash:  "788e0831fcff1f00"
  want_nr90_hash:  "7070f0f0f0f0f03.93c3c2c2c3c39119"
}
