source_file:  "heic.digital Samsung Galaxy A32 3.heic"
want_err:  true
want_fingerprint:  {
  want_kind:  "ImgPHashAzr"
  want_hash:  "c58c6a9da54c24ed"
  want_quality:  20
}
want_fingerprint:  {
  want_kind:  "ImgPHashNr90"
  want_hash:  "e3c3c397cbc38100.f0eaeaaa60a8e8d4"
  want_quality:  20
}
xmp:  {
  comment:  "No XMP data"
}
img_phash:  {
  want_azr_hash:  "c58c6a9da54c24ed"
  want_nr90_hash:  "e3c3c397cbc38100.f0eaeaaa60a8e8d4"
}
