source_file: "IPHONE11hSLI0064NRD.jpg"
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "8cc726cb4720d9bc"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "ff0581c3e7c3c0d9.978a946861c9cecc"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "4IHGw0ZIPA/ILbZmwLF+0T/obJ/2wbF+0E5JZHY/AffFH2xLJp8PEHnvg2xIH4LF7Z2gHm4H5P4+HAYbbskmZGA4gZPnI0Eg"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "XMPDocumentID"
  want_hash: "CEE8F641053E12334BCAE205E585F5DB"
  want_quality: 100
}
exif: {
  want_camera_model: "Apple iPhone 11"
  want_photo_id: "2020-08-06 11:51:13.317 +0000 UTC"
}
xmp: {
  want_document_id: "CEE8F641053E12334BCAE205E585F5DB"
}
img_phash: {
  want_azr_hash: "8cc726cb4720d9bc"
  want_nr90_hash: "ff0581c3e7c3c0d9.978a946861c9cecc"
}
video_phash: {
  comment: "No Video Data"
  skip: true
}
