source_file: "Nikon D3000 2539678715.jpg"
want_fingerprint: {
  want_kind: "EXIFModelSerialPhotoID"
  want_hash: "NIKON D3000 7400454 939 BASIC"
  want_quality: 90
}
want_fingerprint: {
  want_kind: "ImgPHashAzr"
  want_hash: "ec3143461c9a3ee5"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashNr90"
  want_hash: "fbffffbdb13e0c00.3c682bae985337b5"
  want_quality: 20
}
want_fingerprint: {
  want_kind: "ImgPHashAjdnikMH"
  want_hash: "/A5khGHZaluLA4G/Ez8OkD22D+kJbb2zIkyTE4nJ46nD48DI/Gg22JD4fH7w4GHB4n5Gw0lkH/gkn4nIn0gL4Ev20k4HAkzZ"
  want_quality: 20
}
exif: {
  want_camera_model: "NIKON D3000"
  want_camera_serial: "7400454"
  want_photo_id: "939 BASIC"
}
xmp: {
  comment: "No XMP data"
}
img_phash: {
  want_azr_hash: "ec3143461c9a3ee5"
  want_nr90_hash: "fbffffbdb13e0c00.3c682bae985337b5"
}
video_phash: {
  comment: "No Video Data"
}
