source_file:  "Sony A77 2416501744.jpg"
want_fingerprint:  {
  want_kind:  "ImgPHashAzr"
  want_hash:  "fd38a1ca383ea605"
  want_quality:  20
}
want_fingerprint:  {
  want_kind:  "ImgPHashNr90"
  want_hash:  "ff52161e141e0606.4d4d4bcb8a83a32b"
  want_quality:  20
}
want_fingerprint:  {
  want_kind:  "XMPDocumentID"
  want_hash:  "DEF92186DF272963C04750273469F46C"
  want_quality:  100
}
exif:  {
  want_camera_model:  "SONY ILCA-77M2"
  want_photo_id:  "2015-01-28 20:24:27 +0000 UTC"
}
xmp:  {
  want_document_id:  "DEF92186DF272963C04750273469F46C"
}
img_phash:  {
  want_azr_hash:  "fd38a1ca383ea605"
  want_nr90_hash:  "ff52161e141e0606.4d4d4bcb8a83a32b"
}
