source_file: "Sony A6100 4078921458.arw"
want_fingerprint: {
  want_kind: "EXIFModelSerialPhotoID"
  want_hash: "SONY ILCE-6100 5f0000004a0c 214"
  want_quality: 90
}
exif: {
  want_camera_model: "SONY ILCE-6100"
  want_camera_serial: "5f0000004a0c"
  want_photo_id: "214"
}
xmp: {}
img_phash: {
  comment: "TODO: no thumbnail?"
  skip: true
}
video_phash: {
  comment: "No Video Data"
}
