source_file:  "SONY ILCE-6000 214302582 9.ARW"
want_err:  true
want_fingerprint:  {
  want_kind:  "EXIFModelSerialPhotoID"
  want_hash:  "SONY ILCE-6000 214302582 9"
  want_quality:  90
}
exif:  {
  want_camera_model:  "SONY ILCE-6000"
  want_camera_serial:  "214302582"
  want_photo_id:  "9"
}
xmp:  {
  comment:  "No XMP data"
}
