source_file:  "YDSC01923-MFNR_HIGH.JPG"
want_fingerprint:  {
  want_kind:  "EXIFModelSerialPhotoID"
  want_hash:  "SONY ILCA-77M2 173014736 24260"
  want_quality:  90
}
want_fingerprint:  {
  want_kind:  "ImgPHashAzr"
  want_hash:  "116743e1c3e347e1"
  want_quality:  20
}
want_fingerprint:  {
  want_kind:  "ImgPHashNr90"
  want_hash:  "7fcfcfdf20218101.14e26763a730b0f8"
  want_quality:  20
}
want_fingerprint:  {
  want_kind:  "ImgPHashAjdnikCM"
  want_hash:  "mLsw58dwZT/YwVz1TqSbPuC5yh+YlBg+fMxk/OBD8j32HUik1foHvLlQU640t0e9tM+0VdJd2bugzWLnBpVXP5ZUhtohGCU+awUw+Dpd2z2WUUUBR/DEPTZe0UkEHKU7lvwkPZXmybwvgKs83taKu5+o16qt4WA/xEeT+soFdT7Q2r95VtzaPRd54lRBJO898dYqY++B4ru2MTO7dwIwvfYQ8LU4R807l+1pffGSZT9wGJxva+SJPvTY8aNG4e89DUGkq5RJAD5b2BhVhB8HvOARVFKdwEu9NKsV7bVyzbuMbEDoPvFTP3F4x+prqA0+/+oSKfQmjT1iT896xMxxPRj5Ry3V6AG7OVDkrK7hdzwoDDcqnyWzOoonlBGs0lY/9FUhEApMKz5HKBOEvkaTPScI97w2e4M9mPFzuJL9FbuHHBwlZ+2TvGLSzHLYGBm7"
  want_quality:  20
}
want_fingerprint:  {
  want_kind:  "ImgPHashAjdnikMH"
  want_hash:  "E42BKf0hJkz2kgnG/0kjbbWzm8kmwLGzYJI80gbk202xmB582zQ+G22jxJck5H4+Hg/H48Em4A2DY2knE7OBkjDbcmkwmZLJ"
  want_quality:  20
}
exif:  {
  want_camera_model:  "SONY ILCA-77M2"
  want_camera_serial:  "173014736"
  want_photo_id:  "24260"
}
xmp:  {
  comment:  "No XMP data"
}
img_phash:  {
  want_azr_hash:  "116743e1c3e347e1"
  want_nr90_hash:  "7fcfcfdf20218101.14e26763a730b0f8"
}
