// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: fingerprint_test.proto

package fingerprint

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FingerprintTestCase struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SourceFile      string                 `protobuf:"bytes,2,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`
	Comment         []string               `protobuf:"bytes,3,rep,name=comment,proto3" json:"comment,omitempty"`
	Skip            bool                   `protobuf:"varint,4,opt,name=skip,proto3" json:"skip,omitempty"`
	WantErr         bool                   `protobuf:"varint,5,opt,name=want_err,json=wantErr,proto3" json:"want_err,omitempty"`
	WantFingerprint []*WantFingerprint     `protobuf:"bytes,6,rep,name=want_fingerprint,json=wantFingerprint,proto3" json:"want_fingerprint,omitempty"`
	Exif            *EXIFTestCase          `protobuf:"bytes,7,opt,name=exif,proto3" json:"exif,omitempty"`
	Xmp             *XMPTestCase           `protobuf:"bytes,8,opt,name=xmp,proto3" json:"xmp,omitempty"`
	ImgPhash        *ImgPHashTestCase      `protobuf:"bytes,9,opt,name=img_phash,json=imgPhash,proto3" json:"img_phash,omitempty"`
	VideoPhash      *VideoPHashTestCase    `protobuf:"bytes,10,opt,name=video_phash,json=videoPhash,proto3" json:"video_phash,omitempty"`
	Checksum        *ChecksumTestCase      `protobuf:"bytes,11,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Audio           *AudioTestCase         `protobuf:"bytes,12,opt,name=audio,proto3" json:"audio,omitempty"`
	Archive         *ArchiveTestCase       `protobuf:"bytes,13,opt,name=archive,proto3" json:"archive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FingerprintTestCase) Reset() {
	*x = FingerprintTestCase{}
	mi := &file_fingerprint_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FingerprintTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FingerprintTestCase) ProtoMessage() {}

func (x *FingerprintTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprint_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FingerprintTestCase.ProtoReflect.Descriptor instead.
func (*FingerprintTestCase) Descriptor() ([]byte, []int) {
	return file_fingerprint_test_proto_rawDescGZIP(), []int{0}
}

func (x *FingerprintTestCase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FingerprintTestCase) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *FingerprintTestCase) GetComment() []string {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *FingerprintTestCase) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *FingerprintTestCase) GetWantErr() bool {
	if x != nil {
		return x.WantErr
	}
	return false
}

func (x *FingerprintTestCase) GetWantFingerprint() []*WantFingerprint {
	if x != nil {
		return x.WantFingerprint
	}
	return nil
}

func (x *FingerprintTestCase) GetExif() *EXIFTestCase {
	if x != nil {
		return x.Exif
	}
	return nil
}

func (x *FingerprintTestCase) GetXmp() *XMPTestCase {
	if x != nil {
		return x.Xmp
	}
	return nil
}

func (x *FingerprintTestCase) GetImgPhash() *ImgPHashTestCase {
	if x != nil {
		return x.ImgPhash
	}
	return nil
}

func (x *FingerprintTestCase) GetVideoPhash() *VideoPHashTestCase {
	if x != nil {
		return x.VideoPhash
	}
	return nil
}

func (x *FingerprintTestCase) GetChecksum() *ChecksumTestCase {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *FingerprintTestCase) GetAudio() *AudioTestCase {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *FingerprintTestCase) GetArchive() *ArchiveTestCase {
	if x != nil {
		return x.Archive
	}
	return nil
}

type WantFingerprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       []string               `protobuf:"bytes,1,rep,name=comment,proto3" json:"comment,omitempty"`
	WantKind      string                 `protobuf:"bytes,2,opt,name=want_kind,json=wantKind,proto3" json:"want_kind,omitempty"`
	WantHash      string                 `protobuf:"bytes,3,opt,name=want_hash,json=wantHash,proto3" json:"want_hash,omitempty"`
	WantQuality   int32                  `protobuf:"varint,4,opt,name=want_quality,json=wantQuality,proto3" json:"want_quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WantFingerprint) Reset() {
	*x = WantFingerprint{}
	mi := &file_fingerprint_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WantFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantFingerprint) ProtoMessage() {}

func (x *WantFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprint_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantFingerprint.ProtoReflect.Descriptor instead.
func (*WantFingerprint) Descriptor() ([]byte, []int) {
	return file_fingerprint_test_proto_rawDescGZIP(), []int{1}
}

func (x *WantFingerprint) GetComment() []string {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *WantFingerprint) GetWantKind() string {
	if x != nil {
		return x.WantKind
	}
	return ""
}

func (x *WantFingerprint) GetWantHash() string {
	if x != nil {
		return x.WantHash
	}
	return ""
}

func (x *WantFingerprint) GetWantQuality() int32 {
	if x != nil {
		return x.WantQuality
	}
	return 0
}

type EXIFTestCase struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Comment           []string               `protobuf:"bytes,1,rep,name=comment,proto3" json:"comment,omitempty"`
	Skip              bool                   `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	WantCameraModel   string                 `protobuf:"bytes,3,opt,name=want_camera_model,json=wantCameraModel,proto3" json:"want_camera_model,omitempty"`
	WantCameraSerial  string                 `protobuf:"bytes,4,opt,name=want_camera_serial,json=wantCameraSerial,proto3" json:"want_camera_serial,omitempty"`
	WantPhotoId       string                 `protobuf:"bytes,5,opt,name=want_photo_id,json=wantPhotoId,proto3" json:"want_photo_id,omitempty"`
	WantUniquePhotoId bool                   `protobuf:"varint,6,opt,name=want_unique_photo_id,json=wantUniquePhotoId,proto3" json:"want_unique_photo_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EXIFTestCase) Reset() {
	*x = EXIFTestCase{}
	mi := &file_fingerprint_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EXIFTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EXIFTestCase) ProtoMessage() {}

func (x *EXIFTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprint_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EXIFTestCase.ProtoReflect.Descriptor instead.
func (*EXIFTestCase) Descriptor() ([]byte, []int) {
	return file_fingerprint_test_proto_rawDescGZIP(), []int{2}
}

func (x *EXIFTestCase) GetComment() []string {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *EXIFTestCase) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *EXIFTestCase) GetWantCameraModel() string {
	if x != nil {
		return x.WantCameraModel
	}
	return ""
}

func (x *EXIFTestCase) GetWantCameraSerial() string {
	if x != nil {
		return x.WantCameraSerial
	}
	return ""
}

func (x *EXIFTestCase) GetWantPhotoId() string {
	if x != nil {
		return x.WantPhotoId
	}
	return ""
}

func (x *EXIFTestCase) GetWantUniquePhotoId() bool {
	if x != nil {
		return x.WantUniquePhotoId
	}
	return false
}

type XMPTestCase struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Comment        []string               `protobuf:"bytes,1,rep,name=comment,proto3" json:"comment,omitempty"`
	Skip           bool                   `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	WantDocumentId string                 `protobuf:"bytes,3,opt,name=want_document_id,json=wantDocumentId,proto3" json:"want_document_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *XMPTestCase) Reset() {
	*x = XMPTestCase{}
	mi := &file_fingerprint_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XMPTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XMPTestCase) ProtoMessage() {}

func (x *XMPTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprint_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XMPTestCase.ProtoReflect.Descriptor instead.
func (*XMPTestCase) Descriptor() ([]byte, []int) {
	return file_fingerprint_test_proto_rawDescGZIP(), []int{3}
}

func (x *XMPTestCase) GetComment() []string {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *XMPTestCase) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *XMPTestCase) GetWantDocumentId() string {
	if x != nil {
		return x.WantDocumentId
	}
	return ""
}

type ImgPHashTestCase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       []string               `protobuf:"bytes,1,rep,name=comment,proto3" json:"comment,omitempty"`
	Skip          bool                   `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	WantAzrHash   string                 `protobuf:"bytes,3,opt,name=want_azr_hash,json=wantAzrHash,proto3" json:"want_azr_hash,omitempty"`
	WantNr90Hash  string                 `protobuf:"bytes,4,opt,name=want_nr90_hash,json=wantNr90Hash,proto3" json:"want_nr90_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImgPHashTestCase) Reset() {
	*x = ImgPHashTestCase{}
	mi := &file_fingerprint_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImgPHashTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImgPHashTestCase) ProtoMessage() {}

func (x *ImgPHashTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprint_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImgPHashTestCase.ProtoReflect.Descriptor instead.
func (*ImgPHashTestCase) Descriptor() ([]byte, []int) {
	return file_fingerprint_test_proto_rawDescGZIP(), []int{4}
}

func (x *ImgPHashTestCase) GetComment() []string {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *ImgPHashTestCase) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *ImgPHashTestCase) GetWantAzrHash() string {
	if x != nil {
		return x.WantAzrHash
	}
	return ""
}

func (x *ImgPHashTestCase) GetWantNr90Hash() string {
	if x != nil {
		return x.WantNr90Hash
	}
	return ""
}

type VideoPHashTestCase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       []string               `protobuf:"bytes,1,rep,name=comment,proto3" json:"comment,omitempty"`
	Skip          bool                   `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	WantSimhash   string                 `protobuf:"bytes,4,opt,name=want_simhash,json=wantSimhash,proto3" json:"want_simhash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoPHashTestCase) Reset() {
	*x = VideoPHashTestCase{}
	mi := &file_fingerprint_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoPHashTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoPHashTestCase) ProtoMessage() {}

func (x *VideoPHashTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprint_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoPHashTestCase.ProtoReflect.Descriptor instead.
func (*VideoPHashTestCase) Descriptor() ([]byte, []int) {
	return file_fingerprint_test_proto_rawDescGZIP(), []int{5}
}

func (x *VideoPHashTestCase) GetComment() []string {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *VideoPHashTestCase) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *VideoPHashTestCase) GetWantSimhash() string {
	if x != nil {
		return x.WantSimhash
	}
	return ""
}

type ChecksumTestCase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       []string               `protobuf:"bytes,1,rep,name=comment,proto3" json:"comment,omitempty"`
	Skip          bool                   `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Crc32         string                 `protobuf:"bytes,3,opt,name=crc32,proto3" json:"crc32,omitempty"`
	VerifiedCrc32 string                 `protobuf:"bytes,4,opt,name=verified_crc32,json=verifiedCrc32,proto3" json:"verified_crc32,omitempty"`
	Md5           string                 `protobuf:"bytes,5,opt,name=md5,proto3" json:"md5,omitempty"`
	VerifiedMd5   string                 `protobuf:"bytes,6,opt,name=verified_md5,json=verifiedMd5,proto3" json:"verified_md5,omitempty"`
	Sha1          string                 `protobuf:"bytes,7,opt,name=sha1,proto3" json:"sha1,omitempty"`
	VerifiedSha1  string                 `protobuf:"bytes,8,opt,name=verified_sha1,json=verifiedSha1,proto3" json:"verified_sha1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChecksumTestCase) Reset() {
	*x = ChecksumTestCase{}
	mi := &file_fingerprint_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChecksumTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChecksumTestCase) ProtoMessage() {}

func (x *ChecksumTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprint_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChecksumTestCase.ProtoReflect.Descriptor instead.
func (*ChecksumTestCase) Descriptor() ([]byte, []int) {
	return file_fingerprint_test_proto_rawDescGZIP(), []int{6}
}

func (x *ChecksumTestCase) GetComment() []string {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *ChecksumTestCase) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *ChecksumTestCase) GetCrc32() string {
	if x != nil {
		return x.Crc32
	}
	return ""
}

func (x *ChecksumTestCase) GetVerifiedCrc32() string {
	if x != nil {
		return x.VerifiedCrc32
	}
	return ""
}

func (x *ChecksumTestCase) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *ChecksumTestCase) GetVerifiedMd5() string {
	if x != nil {
		return x.VerifiedMd5
	}
	return ""
}

func (x *ChecksumTestCase) GetSha1() string {
	if x != nil {
		return x.Sha1
	}
	return ""
}

func (x *ChecksumTestCase) GetVerifiedSha1() string {
	if x != nil {
		return x.VerifiedSha1
	}
	return ""
}

type AudioTestCase struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Comment []string               `protobuf:"bytes,1,rep,name=comment,proto3" json:"comment,omitempty"`
	Skip    bool                   `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	// Compressed fingerprint as printed by fpcalc.
	WantChromaprint string `protobuf:"bytes,3,opt,name=want_chromaprint,json=wantChromaprint,proto3" json:"want_chromaprint,omitempty"`
	// libchromaprint's chromaprint_hash_fingerprint, as hex.
	WantSimhash   string `protobuf:"bytes,4,opt,name=want_simhash,json=wantSimhash,proto3" json:"want_simhash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioTestCase) Reset() {
	*x = AudioTestCase{}
	mi := &file_fingerprint_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioTestCase) ProtoMessage() {}

func (x *AudioTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprint_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioTestCase.ProtoReflect.Descriptor instead.
func (*AudioTestCase) Descriptor() ([]byte, []int) {
	return file_fingerprint_test_proto_rawDescGZIP(), []int{7}
}

func (x *AudioTestCase) GetComment() []string {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *AudioTestCase) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *AudioTestCase) GetWantChromaprint() string {
	if x != nil {
		return x.WantChromaprint
	}
	return ""
}

func (x *AudioTestCase) GetWantSimhash() string {
	if x != nil {
		return x.WantSimhash
	}
	return ""
}

type ArchiveTestCase struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Comment         []string               `protobuf:"bytes,1,rep,name=comment,proto3" json:"comment,omitempty"`
	Skip            bool                   `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	WantContentTree string                 `protobuf:"bytes,3,opt,name=want_content_tree,json=wantContentTree,proto3" json:"want_content_tree,omitempty"`
	WantContentSet  string                 `protobuf:"bytes,4,opt,name=want_content_set,json=wantContentSet,proto3" json:"want_content_set,omitempty"`
	WantErr         bool                   `protobuf:"varint,5,opt,name=want_err,json=wantErr,proto3" json:"want_err,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ArchiveTestCase) Reset() {
	*x = ArchiveTestCase{}
	mi := &file_fingerprint_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveTestCase) ProtoMessage() {}

func (x *ArchiveTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprint_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveTestCase.ProtoReflect.Descriptor instead.
func (*ArchiveTestCase) Descriptor() ([]byte, []int) {
	return file_fingerprint_test_proto_rawDescGZIP(), []int{8}
}

func (x *ArchiveTestCase) GetComment() []string {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *ArchiveTestCase) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *ArchiveTestCase) GetWantContentTree() string {
	if x != nil {
		return x.WantContentTree
	}
	return ""
}

func (x *ArchiveTestCase) GetWantContentSet() string {
	if x != nil {
		return x.WantContentSet
	}
	return ""
}

func (x *ArchiveTestCase) GetWantErr() bool {
	if x != nil {
		return x.WantErr
	}
	return false
}

var File_fingerprint_test_proto protoreflect.FileDescriptor

const file_fingerprint_test_proto_rawDesc = "" +
	"\n" +
	"\x16fingerprint_test.proto\x12\vfingerprint\"\xda\x04\n" +
	"\x13FingerprintTestCase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vsource_file\x18\x02 \x01(\tR\n" +
	"sourceFile\x12\x18\n" +
	"\acomment\x18\x03 \x03(\tR\acomment\x12\x12\n" +
	"\x04skip\x18\x04 \x01(\bR\x04skip\x12\x19\n" +
	"\bwant_err\x18\x05 \x01(\bR\awantErr\x12G\n" +
	"\x10want_fingerprint\x18\x06 \x03(\v2\x1c.fingerprint.WantFingerprintR\x0fwantFingerprint\x12-\n" +
	"\x04exif\x18\a \x01(\v2\x19.fingerprint.EXIFTestCaseR\x04exif\x12*\n" +
	"\x03xmp\x18\b \x01(\v2\x18.fingerprint.XMPTestCaseR\x03xmp\x12:\n" +
	"\timg_phash\x18\t \x01(\v2\x1d.fingerprint.ImgPHashTestCaseR\bimgPhash\x12@\n" +
	"\vvideo_phash\x18\n" +
	" \x01(\v2\x1f.fingerprint.VideoPHashTestCaseR\n" +
	"videoPhash\x129\n" +
	"\bchecksum\x18\v \x01(\v2\x1d.fingerprint.ChecksumTestCaseR\bchecksum\x120\n" +
	"\x05audio\x18\f \x01(\v2\x1a.fingerprint.AudioTestCaseR\x05audio\x126\n" +
	"\aarchive\x18\r \x01(\v2\x1c.fingerprint.ArchiveTestCaseR\aarchive\"\x88\x01\n" +
	"\x0fWantFingerprint\x12\x18\n" +
	"\acomment\x18\x01 \x03(\tR\acomment\x12\x1b\n" +
	"\twant_kind\x18\x02 \x01(\tR\bwantKind\x12\x1b\n" +
	"\twant_hash\x18\x03 \x01(\tR\bwantHash\x12!\n" +
	"\fwant_quality\x18\x04 \x01(\x05R\vwantQuality\"\xeb\x01\n" +
	"\fEXIFTestCase\x12\x18\n" +
	"\acomment\x18\x01 \x03(\tR\acomment\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip\x12*\n" +
	"\x11want_camera_model\x18\x03 \x01(\tR\x0fwantCameraModel\x12,\n" +
	"\x12want_camera_serial\x18\x04 \x01(\tR\x10wantCameraSerial\x12\"\n" +
	"\rwant_photo_id\x18\x05 \x01(\tR\vwantPhotoId\x12/\n" +
	"\x14want_unique_photo_id\x18\x06 \x01(\bR\x11wantUniquePhotoId\"e\n" +
	"\vXMPTestCase\x12\x18\n" +
	"\acomment\x18\x01 \x03(\tR\acomment\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip\x12(\n" +
	"\x10want_document_id\x18\x03 \x01(\tR\x0ewantDocumentId\"\x8a\x01\n" +
	"\x10ImgPHashTestCase\x12\x18\n" +
	"\acomment\x18\x01 \x03(\tR\acomment\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip\x12\"\n" +
	"\rwant_azr_hash\x18\x03 \x01(\tR\vwantAzrHash\x12$\n" +
	"\x0ewant_nr90_hash\x18\x04 \x01(\tR\fwantNr90Hash\"|\n" +
	"\x12VideoPHashTestCase\x12\x18\n" +
	"\acomment\x18\x01 \x03(\tR\acomment\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip\x12!\n" +
	"\fwant_simhash\x18\x04 \x01(\tR\vwantSimhashJ\x04\b\x03\x10\x04R\x0fwant_ricop_hash\"\xeb\x01\n" +
	"\x10ChecksumTestCase\x12\x18\n" +
	"\acomment\x18\x01 \x03(\tR\acomment\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip\x12\x14\n" +
	"\x05crc32\x18\x03 \x01(\tR\x05crc32\x12%\n" +
	"\x0everified_crc32\x18\x04 \x01(\tR\rverifiedCrc32\x12\x10\n" +
	"\x03md5\x18\x05 \x01(\tR\x03md5\x12!\n" +
	"\fverified_md5\x18\x06 \x01(\tR\vverifiedMd5\x12\x12\n" +
	"\x04sha1\x18\a \x01(\tR\x04sha1\x12#\n" +
	"\rverified_sha1\x18\b \x01(\tR\fverifiedSha1\"\x8b\x01\n" +
	"\rAudioTestCase\x12\x18\n" +
	"\acomment\x18\x01 \x03(\tR\acomment\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip\x12)\n" +
	"\x10want_chromaprint\x18\x03 \x01(\tR\x0fwantChromaprint\x12!\n" +
	"\fwant_simhash\x18\x04 \x01(\tR\vwantSimhash\"\xb0\x01\n" +
	"\x0fArchiveTestCase\x12\x18\n" +
	"\acomment\x18\x01 \x03(\tR\acomment\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip\x12*\n" +
	"\x11want_content_tree\x18\x03 \x01(\tR\x0fwantContentTree\x12(\n" +
	"\x10want_content_set\x18\x04 \x01(\tR\x0ewantContentSet\x12\x19\n" +
	"\bwant_err\x18\x05 \x01(\bR\awantErrB(Z&github.com/rpajarola/dedup/fingerprintb\x06proto3"

var (
	file_fingerprint_test_proto_rawDescOnce sync.Once
	file_fingerprint_test_proto_rawDescData []byte
)

func file_fingerprint_test_proto_rawDescGZIP() []byte {
	file_fingerprint_test_proto_rawDescOnce.Do(func() {
		file_fingerprint_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fingerprint_test_proto_rawDesc), len(file_fingerprint_test_proto_rawDesc)))
	})
	return file_fingerprint_test_proto_rawDescData
}

var file_fingerprint_test_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_fingerprint_test_proto_goTypes = []any{
	(*FingerprintTestCase)(nil), // 0: fingerprint.FingerprintTestCase
	(*WantFingerprint)(nil),     // 1: fingerprint.WantFingerprint
	(*EXIFTestCase)(nil),        // 2: fingerprint.EXIFTestCase
	(*XMPTestCase)(nil),         // 3: fingerprint.XMPTestCase
	(*ImgPHashTestCase)(nil),    // 4: fingerprint.ImgPHashTestCase
	(*VideoPHashTestCase)(nil),  // 5: fingerprint.VideoPHashTestCase
	(*ChecksumTestCase)(nil),    // 6: fingerprint.ChecksumTestCase
	(*AudioTestCase)(nil),       // 7: fingerprint.AudioTestCase
	(*ArchiveTestCase)(nil),     // 8: fingerprint.ArchiveTestCase
}
var file_fingerprint_test_proto_depIdxs = []int32{
	1, // 0: fingerprint.FingerprintTestCase.want_fingerprint:type_name -> fingerprint.WantFingerprint
	2, // 1: fingerprint.FingerprintTestCase.exif:type_name -> fingerprint.EXIFTestCase
	3, // 2: fingerprint.FingerprintTestCase.xmp:type_name -> fingerprint.XMPTestCase
	4, // 3: fingerprint.FingerprintTestCase.img_phash:type_name -> fingerprint.ImgPHashTestCase
	5, // 4: fingerprint.FingerprintTestCase.video_phash:type_name -> fingerprint.VideoPHashTestCase
	6, // 5: fingerprint.FingerprintTestCase.checksum:type_name -> fingerprint.ChecksumTestCase
	7, // 6: fingerprint.FingerprintTestCase.audio:type_name -> fingerprint.AudioTestCase
	8, // 7: fingerprint.FingerprintTestCase.archive:type_name -> fingerprint.ArchiveTestCase
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_fingerprint_test_proto_init() }
func file_fingerprint_test_proto_init() {
	if File_fingerprint_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fingerprint_test_proto_rawDesc), len(file_fingerprint_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fingerprint_test_proto_goTypes,
		DependencyIndexes: file_fingerprint_test_proto_depIdxs,
		MessageInfos:      file_fingerprint_test_proto_msgTypes,
	}.Build()
	File_fingerprint_test_proto = out.File
	file_fingerprint_test_proto_goTypes = nil
	file_fingerprint_test_proto_depIdxs = nil
}
