source_file: "../../testdata/Apple iPhone 4 B9AEA6B8FE2068118083C9A827F66721.jpg"
skip: true

want_camera_model: "Apple iPhone 4"
want_camera_serial: "fixme"
want_photo_id: "fixme"
want_photo_id_fp: "fixme"
want_photo_id_fp_quality: 0
