source_file: "../../testdata/Apple iPhone 7 AF4B4E28-9113-4656-BBEF-96F7CBC448CE heic.jpg"
skip: true

want_camera_model: "Apple iPhone 7"
want_camera_serial: "fixme"
want_photo_id: "fixme"
want_photo_id_fp: "fixme"
want_photo_id_fp_quality: 0
