source_file: "../../testdata/Apple iPhone 7 AF4B4E28-9113-4656-BBEF-96F7CBC448CE heic.jpg"

want_fingerprint {
	want_kind: "EXIFModelSerialPhotoID"
	want_hash: "Apple iPhone 7  AF4B4E28-9113-4656-BBEF-96F7CBC448CE"
	want_quality: 100
}

exif {
	want_camera_model: "Apple iPhone 7"
	want_camera_serial: ""
	want_photo_id: "AF4B4E28-9113-4656-BBEF-96F7CBC448CE"
	want_unique_photo_id: true
}
