source_file: "../testdata/Apple iPhone 12 Pro heic 2.jpg"

want_fingerprint {
	want_kind: "EXIFModelSerialPhotoID"
	want_hash: "Apple iPhone 12 Pro  8836E8B5-A132-4292-8D7D-87CCE1CACD2A"
	want_quality: 100
}

exif {
	want_camera_model: "Apple iPhone 12 Pro"
	want_camera_serial: ""
	want_photo_id: "8836E8B5-A132-4292-8D7D-87CCE1CACD2A"
	want_unique_photo_id: true
}

xmp {
	# No XMP data
	want_document_id: ""
}
