source_file:  "../testdata/Canon EOS DIGITAL REBEL XSi 520116695 a24f0db7-9fc8-40b2-bbc2-9bc64758fb38.jpg"
want_fingerprint:  {
  want_kind:  "EXIFModelSerialPhotoID"
  want_hash:  "Canon EOS DIGITAL REBEL XSi 520116695 2010-10-12 12:47:51 +0000 UTC"
  want_quality:  80
}
want_fingerprint:  {
  want_kind:  "XMPDocumentID"
  want_hash:  "a24f0db7-9fc8-40b2-bbc2-9bc64758fb38"
  want_quality:  100
}
exif:  {
  want_camera_model:  "Canon EOS DIGITAL REBEL XSi"
  want_camera_serial:  "520116695"
  want_photo_id:  "2010-10-12 12:47:51 +0000 UTC"
}
xmp:  {
  want_document_id:  "a24f0db7-9fc8-40b2-bbc2-9bc64758fb38"
}
img_phash:  {
  comment:  "no image data"
  skip:  true
}
