source_file:  "../testdata/Canon PowerShot SX230 HS a0d2aa0209df07a36eb503a1e039ca22.jpg"
want_fingerprint:  {
  want_kind:  "EXIFModelSerialPhotoID"
  want_hash:  "Canon PowerShot SX230 HS  a0d2aa0209df07a36eb503a1e039ca22"
  want_quality:  100
}
exif:  {
  want_camera_model:  "Canon PowerShot SX230 HS"
  want_photo_id:  "a0d2aa0209df07a36eb503a1e039ca22"
  want_unique_photo_id:  true
}
xmp:  {}
img_phash:  {
  comment:  "no image data"
  skip:  true
}
