source_file: "../testdata/Canon EOS-1D Mark II 237359 227906.jpg"
skip: true  # TODO: implement Canon Shutter Count

exif {
	want_camera_model: "Canon EOS-1D Mark II"
	want_camera_serial: "237359"
	want_photo_id: "227906"  # Shutter Count
}
