source_file: "../../testdata/Canon PowerShot SX230 HS a0d2aa0209df07a36eb503a1e039ca22.jpg"

want_camera_model: "Canon PowerShot SX230 HS"
want_camera_serial: ""
want_photo_id: "a0d2aa0209df07a36eb503a1e039ca22"
want_unique_photo_id: true
want_photo_id_fp: "Canon PowerShot SX230 HS  a0d2aa0209df07a36eb503a1e039ca22"
want_photo_id_fp_quality: 100
