source_file: "../../testdata/NIKON D300 3005346 1803_nef.jpg"

want_camera_model: "NIKON D300"
want_camera_serial: "3005346"
want_photo_id: "1803 RAW"
want_photo_id_fp: "NIKON D300 3005346 1803 RAW"
want_photo_id_fp_quality: 90
