source_file:  "../testdata/NIKON COOLPIX AW100 none.jpg"
exif:  {
  want_camera_model:  "NIKON COOLPIX AW100"
  want_photo_id:  "2013-02-06 21:26:36 +0000 UTC NORMAL"
}
xmp:  {
  comment:  "No XMP data"
}
