source_file: "../testdata/NIKON COOLPIX P1000 30001701 1.jpg"

want_fingerprint {
        want_kind: "EXIFModelSerialPhotoID"
        want_hash: "NIKON COOLPIX P1000 30001701 2018-09-18 20:46:11 +0000 UTC FINE"
        want_quality: 80
}

exif {
	want_camera_model: "NIKON COOLPIX P1000"
	want_camera_serial: "30001701"
	want_photo_id: "2018-09-18 20:46:11 +0000 UTC FINE"
}
