source_file: "../../testdata/Panasonic DMC-FZ28 7f050b14-53d6-4d30-9672-20e3a0f6ff94.jpg"

exif {
	want_camera_model: "Panasonic DMC-FZ28"
	want_camera_serial: ""
	want_photo_id: "2009-07-21 22:16:00 +0000 UTC"
}

xmp {
	want_document_id: "7f050b14-53d6-4d30-9672-20e3a0f6ff94"
}
