source_file: "../testdata/Samsung SM-A326B heic 1.jpg"

exif {
	want_camera_model: "samsung SM-A326B"
	want_camera_serial: ""
	want_photo_id: "2023-12-13 13:03:39.016 +0000 UTC"
}

xmp {
	# no XMP data
	want_document_id: ""
}
