source_file: "../../testdata/Samsung Galaxy Nexus OAEL01 21080E7590649EE95C9E9C6F3C98B425.jpg"

want_fingerprint {
	want_kind: "EXIFModelSerialPhotoID"
	want_hash: "Samsung Galaxy Nexus  OAEL01"
	want_quality: 100
}
want_fingerprint {
        want_kind: "XMPDocumentID"
        want_hash: "21080E7590649EE95C9E9C6F3C98B425"
        want_quality: 100
}

exif {
	want_camera_model: "Samsung Galaxy Nexus"
	want_camera_serial: ""
	# photo id might be just the camera id"
	want_photo_id: "OAEL01"
	want_unique_photo_id: true
}
