source_file: "/Users/ricop/src/dedup/testdata/SONY Alpha 77 II 7613018102 24265.jpg"
exif: {
  want_camera_model: "SONY ILCA-77M2"
  want_photo_id: "2015-06-04 21:04:26 +0000 UTC"
  # TODO: makernotes parsing fails
  # want_camera_serial: "7613018102"
  # want_photo_id: "24265"
}
