source_file: "../../testdata/Sony Ericsson K800i none.jpg"
skip: true

want_camera_model: "Sony Ericsson K800i"
want_camera_serial: ""
want_photo_id: ""
want_photo_id_fp: ""
want_photo_id_fp_quality: 0
