source_file:  "../testdata/SONY A7s III jpeg none 6d2a79cc-d7bf-416d-bdb4-643a667b1ef4.jpg"
comment:  "pre-release model of SONY A7s III"
want_fingerprint:  {
  want_kind:  "XMPDocumentID"
  want_hash:  "A1B59EAF9BAAEC3F0C97603358445EF3"
  want_quality:  100
}
exif:  {
  want_camera_model:  "SONY MODEL-NAME"
  want_photo_id:  "2022-09-09 21:29:51.627 +0000 UTC"
}
xmp:  {
  comment:  "TODO"
  comment:  "OriginalDocumentID = A1B59EAF9BAAEC3F0C97603358445EF3"
  comment:  "DocumentID = xmp.did:6d2a79cc-d7bf-416d-bdb4-643a667b1ef4"
  comment:  "InstanceID = xmp.iid:6d2a79cc-d7bf-416d-bdb4-643a667b1ef4"
  comment:  "HistoryInstanceID = xmp.iid:58fe1404-10fe-4f7e-afc9-84155fa2fecc"
  comment:  "HistoryInstanceID = xmp.iid:29d5c88b-b77f-4175-9587-9e8cf3388f80"
  comment:  "HistoryInstanceID = xmp.iid:6d2a79cc-d7bf-416d-bdb4-643a667b1ef4"
  comment:  "LookUUID = B952C231111CD8E0ECCF14B86BAA7077"
  want_document_id:  "A1B59EAF9BAAEC3F0C97603358445EF3"
}
img_phash:  {
  comment:  "no image data"
  skip:  true
}
