source_file:  "../testdata/SONY A7s III 20221872 0.jpg"
comment:  "pre-release model of SONY A7s III"
comment:  "want_fingerprint {"
comment:  "  want_kind: \"EXIFModelSerialPhotoID\""
comment:  "  want_hash: \"SONY MODEL-NAME 45810378 0\""
comment:  "  want_quality: 90"
comment:  "}"
exif:  {
  want_camera_model:  "SONY MODEL-NAME"
  want_photo_id:  "2022-09-09 21:29:51.627 +0000 UTC"
}
xmp:  {}
