source_file: "../../testdata/Sony Ericsson ST17i FAAB315EB2DA9C530FB5BF837EEB7DDA.jpg"

exif {
	want_camera_model: "Sony Ericsson ST17i"
	want_camera_serial: ""
	want_photo_id: "2011-12-11 16:41:52 +0000 UTC"
}
