source_file: "../../testdata/SONY Alpha 77 II 7613018102 24265.jpg"
skip: true  # TODO: need makernotes

want_fingerprint {
	want_kind: "EXIFModelSerialPhotoID"
	want_hash: "SONY ILCA-77M2 7613018102 24265"
	want_quality: 90
}

exif {
	want_camera_model: "SONY ILCA-77M2"
	want_camera_serial: "7613018102"
	want_photo_id: "24265"
}
