source_file: "../../testdata/SONY A6100 950007412 214_arw.jpg"
skip: true  # TODO: implement sony makernotes

exif {
	want_camera_model: "SONY ILCE-6100"
	want_camera_serial: "950007412 fixme"
	want_photo_id: "214"
}
